In [1]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go 
from plotly.subplots import make_subplots

## data exploration

In [2]:
df=pd.read_csv("../data/Teen_Mental_Health_Dataset.csv")
df.head(5)

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       1200 non-null   int64
 1   gender                    1200 non-null   str
 2   daily_social_media_hours  1200 non-null   float64
 3   platform_usage            1200 non-null   str
 4   sleep_hours               1200 non-null   float64
 5   screen_time_before_sleep  1200 non-null   float64
 6   academic_performance      1200 non-null   float64
 7   physical_activity         1200 non-null   float64
 8   social_interaction_level  1200 non-null   str
 9   stress_level              1200 non-null   int64
 10  anxiety_level             1200 non-null   int64
 11  addiction_level           1200 non-null   int64
 12  depression_label          1200 non-null   int64
dtypes: float64(5), int64(5), str(3)
memory usage: 122.0 KB

In [4]:
df.shape
df.describe()

,age,daily_social_media_hours,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,stress_level,anxiety_level,addiction_level,depression_label
count,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000
mean,15.928333,4.536667,6.449417,1.740333,2.990383,1.014500,5.445833,5.636667,5.565000,0.025833
std,2.021947,2.029599,1.442677,0.716660,0.576758,0.582185,2.903290,2.859453,2.830627,0.158704
min,13.000000,1.000000,4.000000,0.500000,2.000000,0.000000,1.000000,1.000000,1.000000,0.000000
25%,14.000000,2.800000,5.200000,1.100000,2.500000,0.500000,3.000000,3.000000,3.000000,0.000000
50%,16.000000,4.500000,6.500000,1.800000,2.990000,1.000000,5.000000,6.000000,6.000000,0.000000
75%,18.000000,6.300000,7.600000,2.400000,3.480000,1.500000,8.000000,8.000000,8.000000,0.000000
max,19.000000,8.000000,9.000000,3.000000,4.000000,2.000000,10.000000,10.000000,10.000000,1.000000

In [5]:
#df.isnull().sum()

## data visualation

In [6]:
df.head()

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0

In [7]:
#Soru 1: Katılımcıların en çok tercih ettiği sosyal medya platformları nelerdir? (Hangi platformun kullanıcı sayısı daha fazla?)
#Önerilen Grafik: Bar Plot (Çubuk Grafik) veya Pie Chart (Pasta Grafik)
most_used_platforms=df.platform_usage.value_counts()
most_used_platforms=pd.DataFrame(most_used_platforms).reset_index()
fig=px.bar(
    most_used_platforms,
    y="platform_usage",
    x="count",
    orientation="h",
    color="platform_usage",
    color_discrete_sequence=["#e6e600","#7d8887","#380e0e"],
    barmode="stack",
    text="count"
)
fig.update_traces(
    marker_line_color="black",
    marker_line_width=2,
    textposition="outside",

)
fig.update_yaxes(tickangle=45)
fig.update_layout(
    yaxis_title="Platform Names",
    xaxis_title="User Count",
    title="Most Used Plotforms", 
    height=400,


)
fig.show()

In [8]:
#Soru 2: Veri setindeki katılımcıların yaş dağılımı nasıl bir eğilim gösteriyor? Gençler mi ağırlıkta yoksa daha homojen bir dağılım mı var?
#Önerilen Grafik: Histogram
age_distribution=df.age.value_counts()
age_distribution=pd.DataFrame(age_distribution).reset_index()
age_distribution['age_label'] = "Age " + age_distribution['age'].astype(str)
fig=px.pie(
    age_distribution,
    names="age_label",
    values="count",
    hole=0.4,
    color="count",
    title="Age Distribution",
)
fig.update_traces(
    textposition="inside",
    textinfo="label+percent",
    pull=[0,0,0,0.3,0,0],
    marker=dict(line=dict(color='black', width=1.5))
)
fig.update_layout(
    paper_bgcolor="#60818e",
    title_font_color="lightcyan",
    title_font_size=24,
    font_color="white"
)
fig.show()

In [9]:
#Soru 3: Günlük sosyal medya kullanım süresi (daily_social_media_hours) arttıkça uyku süresi (sleep_hours) azalıyor mu?
#Önerilen Grafik: Scatter Plot (Dağılım Grafiği) - İstersen içine bir trend çizgisi (regresyon) de ekleyebilirsin.
fig=px.scatter(
    df,
    x="daily_social_media_hours",
    y="sleep_hours",
    marginal_x="box",
    marginal_y="violin",
    color="gender",
    trendline="ols",
    opacity=0.9,
    labels={
        "daily_social_media_hours": "Daily Social Media Hours",
        "sleep_hours": "Sleep Hours",
        "gender": "Gender"
    }
)
fig.update_layout(
    title_font_size=20
)
fig.show()

In [26]:
#Soru 4: Depresyon riski taşıyan (depression_label = 1) ve taşımayan (0) kişilerin uyku öncesi ekran süreleri (screen_time_before_sleep) arasında belirgin bir fark var mı?
#Önerilen Grafik: Box Plot (Kutu Grafiği) veya Violin Plot - Aykırı değerleri (outliers) görmek için harikadır
fig=px.violin(
    df,
    x="depression_label",
    y="screen_time_before_sleep",
    color="depression_label",
    box=True,
    color_discrete_sequence=["#7d8887", "#380e0e"],
)
fig.update_layout(
    xaxis_title="Effects of depression",
    yaxis_title="Screen Time Before Sleep",
    showlegend=False
)
fig.show()

In [ ]:
#Soru 5: Cinsiyete (gender) göre stres seviyesi (stress_level) ortalamaları nasıl değişiyor?
#Önerilen Grafik: Bar Plot (ortalama değerler ile)
group_df=df.groupby("gender")["stress_level"].mean().reset_index()
fig=px.bar(
    group_df,
    x="gender",
    y="stress_level",
    color="gender",
    color_discrete_sequence=["#7d8887","#380e0e"],
    title="Average Stress Level by Gender",
)
fig.update_traces(
    marker_line_color="black",
    marker_line_width=2,

)
fig.update_layout(
    xaxis_title="Gender",
    yaxis_title="Average Stress Level",
   
)
fig.show()