In [2]:
import pandas as pd
import numpy as np
st_per=pd.read_csv("./data/student_performance_updated_1000.csv")
st_per.head()

,StudentID,Name,Gender,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,ParentalSupport,FinalGrade,Study Hours,Attendance (%),Online Classes Taken
0,1.0,John,Male,85.0,15.0,78.0,1.0,High,80.0,4.8,59.0,False
1,2.0,Sarah,Female,90.0,20.0,85.0,2.0,Medium,87.0,2.2,70.0,True
2,3.0,Alex,Male,78.0,10.0,65.0,0.0,Low,68.0,4.6,92.0,False
3,4.0,Michael,Male,92.0,25.0,90.0,3.0,High,92.0,2.9,96.0,False
4,5.0,Emma,Female,NaN,18.0,82.0,2.0,Medium,85.0,4.1,97.0,True

In [3]:
#step-1
shape=st_per.shape
dtypes=st_per.dtypes
print(f"shape:{shape},data types:{dtypes}")

shape:(1000, 12),data types:StudentID                    float64
Name                             str
Gender                           str
AttendanceRate               float64
StudyHoursPerWeek            float64
PreviousGrade                float64
ExtracurricularActivities    float64
ParentalSupport                  str
FinalGrade                   float64
Study Hours                  float64
Attendance (%)               float64
Online Classes Taken          object
dtype: object

In [4]:
nan_rows_colmns=st_per.isnull().sum()
nan_rows_colmns

StudentID                    40
Name                         34
Gender                       48
AttendanceRate               40
StudyHoursPerWeek            50
PreviousGrade                33
ExtracurricularActivities    43
ParentalSupport              22
FinalGrade                   40
Study Hours                  24
Attendance (%)               41
Online Classes Taken         25
dtype: int64

In [5]:
#step2
gender_unique=st_per.Gender.unique()
support_unique=st_per.ParentalSupport.unique()
print(f"gender unique values:{gender_unique},parrent support unique values:{support_unique}")

gender unique values:<StringArray>
['Male', 'Female', nan]
Length: 3, dtype: str,parrent support unique values:<StringArray>
['High', 'Medium', 'Low', nan]
Length: 4, dtype: str

In [6]:
db_values=st_per.duplicated().sum()
st_per["Online Classes Taken"].value_counts()

Online Classes Taken
True     495
False    480
Name: count, dtype: int64

In [7]:
st_per

,StudentID,Name,Gender,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,ParentalSupport,FinalGrade,Study Hours,Attendance (%),Online Classes Taken
0,1.0,John,Male,85.0,15.0,78.0,1.0,High,80.0,4.8,59.0,False
1,2.0,Sarah,Female,90.0,20.0,85.0,2.0,Medium,87.0,2.2,70.0,True
2,3.0,Alex,Male,78.0,10.0,65.0,0.0,Low,68.0,4.6,92.0,False
3,4.0,Michael,Male,92.0,25.0,90.0,3.0,High,92.0,2.9,96.0,False
4,5.0,Emma,Female,NaN,18.0,82.0,2.0,Medium,85.0,4.1,97.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...
995,NaN,Kenneth Murray,Male,85.0,20.0,NaN,1.0,High,72.0,0.8,80.0,True
996,4497.0,Amy Stout,Female,91.0,NaN,86.0,0.0,High,90.0,3.9,80.0,True
997,1886.0,NaN,Male,85.0,8.0,82.0,2.0,Low,68.0,0.4,54.0,False
998,7636.0,Joseph Sherman,Male,88.0,17.0,60.0,2.0,High,85.0,0.9,53.0,True
999,8021.0,Maria Walls,Female,88.0,10.0,90.0,1.0,Medium,NaN,2.4,94.0,True

In [8]:
#step3
"""

StudentID                    40drop x
Name                         34drop x
Gender                       48mod
AttendanceRate               40 x
StudyHoursPerWeek            50x
PreviousGrade                33
ExtracurricularActivities    43
ParentalSupport              22
FinalGrade                   40 medyan /mean x
Study Hours                  24medyan/ mean x
Attendance (%)               41
Online Classes Taken         25

"""

'\n\nStudentID                    40drop x\nName                         34drop x\nGender                       48mod\nAttendanceRate               40 x\nStudyHoursPerWeek            50x\nPreviousGrade                33\nExtracurricularActivities    43\nParentalSupport              22\nFinalGrade                   40 medyan /mean x\nStudy Hours                  24medyan/ mean x\nAttendance (%)               41\nOnline Classes Taken         25\n\n'

In [9]:
#drop
st_per.dropna(subset=["StudentID","Name"],inplace=True)
#fill


st_per['AttendanceRate'] = st_per['AttendanceRate'].fillna(
    st_per.groupby('Online Classes Taken')['AttendanceRate'].transform('median')
)
st_per["FinalGrade"]=st_per["FinalGrade"].fillna(st_per["FinalGrade"].mean())
st_per["Study Hours"]=st_per["Study Hours"].fillna(st_per["Study Hours"].mean())
st_per["StudyHoursPerWeek"]=st_per["StudyHoursPerWeek"].fillna(st_per.groupby("FinalGrade")["StudyHoursPerWeek"].transform("median"))
st_per["AttendanceRate"]=st_per["AttendanceRate"].fillna(st_per["AttendanceRate"].median())

In [10]:
st_per["PreviousGrade"]=st_per["PreviousGrade"].fillna(st_per.groupby("FinalGrade")["PreviousGrade"].transform("median"))

In [12]:
st_per["ExtracurricularActivities"]=st_per["ExtracurricularActivities"].fillna(0.0)

In [ ]:
probs=st_per["ParentalSupport"].value_counts(normalize=True)
missing_mask = st_per['ParentalSupport'].isnull()
missing_count = missing_mask.sum()

random_values = np.random.choice(probs.index, size=missing_count, p=probs.values, replace=True)
st_per.loc[missing_mask, "ParentalSupport"] = random_values

In [23]:
st_per.isnull().sum()
import plotly.express as px
px.box(
    st_per,
    x="Attendance (%)"
)

In [25]:
st_per=st_per[st_per["Attendance (%)"]<=100]
px.box(
    st_per,
    x="Attendance (%)"
)

In [26]:
st_per["Attendance (%)"]=st_per["Attendance (%)"].fillna(st_per["Attendance (%)"].median())

In [31]:
st_per["Online Classes Taken"].value_counts()
st_per["Online Classes Taken"]=st_per["Online Classes Taken"].fillna("True")

In [34]:
st_per["Gender"].value_counts()
st_per["Gender"]=st_per["Gender"].fillna("Male")

In [35]:
st_per.isnull().sum()

StudentID                    0
Name                         0
Gender                       0
AttendanceRate               0
StudyHoursPerWeek            0
PreviousGrade                0
ExtracurricularActivities    0
ParentalSupport              0
FinalGrade                   0
Study Hours                  0
Attendance (%)               0
Online Classes Taken         0
dtype: int64